apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    readinessProbe:
      initialDelaySeconds: 5
      httpGet:
        path: /healthy #given by devs
        port: 80
      