apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-claim-gold
spec:
  accessModes:
  - ReadwriteOnce
  resources:
    requests:
      storage: 20Gi
 storageClassName: gold

#apply the above yaml files and use kubectl get pv,pvc,sc