apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-example
spec:
  selector:
    matchLabels:
      color: green
  template:
    metadata:
      labels: 
        color: green
    spec:
      containers:
        - image: devopswithcloudhub/python_webpage:blue
          name: greenpod
          ports:
            - containerPort: 8080