apiVersion: apps/v1
kind: Deployment
metadata: 
  name: recreate-deploy
spec: 
  template:
    metadata:
      labels:
        type: recreate
    spec: 
      containers:
      - image: devopswithcloudhub/python_webpage:greencont
        name: pythoncont
  replicas: 5
  selector:
    matchLabels:
      type: recreate
  strategy:
    type: Recreate
    