apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: developer-role
  namespace: bout-dev
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create"]

---
#RoleBinding
# u need to already have a role created before creating a rolebinding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: bout-dev
subjects:
# You can specify more than one "subject"
- kind: User
  name: #name of the user
   # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role #role/clusterrole
  name: #must match the name of the role u wish to bind
  apiGroup: rbac.authorization.k8s.io

