apiVersion: v1
kind: Service
metadata:
  name: svc-color
spec:
  selector:
    color: green #WHICH pods i should route the traffc
  type: NodePort
  ports:
    - port: 80 #svc port
      protocol: TCP
      targetPort: 8080 #my container port
