apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      labels:
        env: test
    spec: 
      containers:
      - image: nginx
        name: nginx
      nodeSelector:
        disktype: ssd